package com.itau.api.renegociation.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;

import java.util.List;

@DynamoDBTable(tableName = "EffectiveRenegociation")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class EffectiveRenegociationModel {

    private String id;
    private String documentId;
    private String transactionId;
    private String amount;
    private String discountPercentage;
    private String discountAmount;
    private String effectiveValue;
    private String date;
    private String plots;
    private String installmentValue;
    private String status;
    private List<String> debts;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getDocumentId() {
        return documentId;
    }

    @DynamoDBAttribute
    public String getTransactionId() {
        return transactionId;
    }

    @DynamoDBAttribute
    public String getAmount() {
        return amount;
    }

    @DynamoDBAttribute
    public String getDiscountPercentage() {
        return discountPercentage;
    }

    @DynamoDBAttribute
    public String getDiscountAmount() {
        return discountAmount;
    }

    @DynamoDBAttribute
    public String getEffectiveValue() {
        return effectiveValue;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute
    public List<String> getDebts() {
        return debts;
    }

    @CreatedDate
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public String getDate() {
        return date;
    }

    @DynamoDBAttribute
    public String getPlots() {
        return plots;
    }

    @DynamoDBAttribute
    public String getInstallmentValue() {
        return installmentValue;
    }

    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public void setDiscountPercentage(String discountPercentage) {
        this.discountPercentage = discountPercentage;
    }

    public void setDiscountAmount(String discountAmount) {
        this.discountAmount = discountAmount;
    }

    public void setEffectiveValue(String effectiveValue) {
        this.effectiveValue = effectiveValue;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setPlots(String plots) {
        this.plots = plots;
    }

    public void setInstallmentValue(String installmentValue) {
        this.installmentValue = installmentValue;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setStatus(String id) {
        this.status = status;
    }

    public void setDebts(List<String> debts) {
        this.debts = debts;
    }
}