package com.itau.api.renegociation.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;

import java.util.List;

@DynamoDBTable(tableName = "SimulationRenegociation")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SimulationModel {
    private String id;
    private String date;
    private String value;
    private String discountPercent;
    private String plots;
    private String installmentValue;
    private String documentId;
    private List<String> debts;
    private String status;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @CreatedDate
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @DynamoDBAttribute
    public String getValue() {
        return value;
    }


    public void setValue(String value) {
        this.value = value;
    }

    @DynamoDBAttribute
    public String getDiscountPercent() {
        return discountPercent;
    }

    public void setDiscountPercent(String discountPercent) {
        this.discountPercent = discountPercent;
    }

    @DynamoDBAttribute
    public String getPlots() {
        return plots;
    }

    public void setPlots(String plots) {
        this.plots = plots;
    }

    @DynamoDBAttribute
    public String getInstallmentValue() {
        return installmentValue;
    }

    public void setInstallmentValue(String installmentValue) {
        this.installmentValue = installmentValue;
    }

    @DynamoDBAttribute
    public List<String> getDebts() {
        return debts;
    }

    public void setDebts(List<String> debts) {
        this.debts = debts;
    }


    @DynamoDBAttribute
    public String getDocumentId() {
        return documentId;
    }

    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
